### ISSUE TITLE
Property--Add--Given thumbnail is showing wrong in view page

### ISSUE THREAD

**Issue by noelrahul** [noelrahul/Worklease-latest-version#27]
![image](https://user-images.githubusercontent.com/44424731/93586620-310d0880-f9c6-11ea-958f-971378dcc3bd.png)
![image](https://user-images.githubusercontent.com/44424731/93586732-5f8ae380-f9c6-11ea-8895-5ace3133fb06.png)

**Comment by ravicstpl18** [comment]
Please check the screenshot below
http://prntscr.com/uji5br
