### ISSUE TITLE
Lead CRM--Initiate booking--Property is selected but still showing in property listings field

### ISSUE THREAD

**Issue by noelrahul** [noelrahul/Worklease-latest-version#32]
![image](https://user-images.githubusercontent.com/44424731/93590790-c4e1d300-f9cc-11ea-9d25-15a7bb320105.png)

**Comment by ravicstpl18** [comment]
Yes It will be shown. After design implementation I will explain.

**Comment by ravicstpl18** [comment]
**Can Ignore -----Client Explained**
