### ISSUE TITLE
Employee--Booking inititating--Loading is taking more time

### ISSUE THREAD

**Issue by noelrahul** [noelrahul/Worklease-latest-version#46]
![image](https://user-images.githubusercontent.com/44424731/93751169-4a0df780-fc1a-11ea-8b70-e56ccbb24ff9.png)
![image](https://user-images.githubusercontent.com/44424731/93751212-57c37d00-fc1a-11ea-8f8e-4d88fa3f8f0a.png)

**Comment by ravicstpl18** [comment]
Check with the new record
