### ISSUE TITLE
Employee-- Add lead-- Leads are not showing

### ISSUE THREAD

**Issue by noelrahul** [noelrahul/Worklease-latest-version#48]
![image](https://user-images.githubusercontent.com/44424731/93754301-200b0400-fc1f-11ea-819e-3d99aa58b911.png)

**Comment by ravicstpl18** [comment]
Admin can only add leads.
-->no access for employee according to the client requirement

**Comment by ravicstpl18** [comment]
**Can Ignore ----Client Explained**
